// Writes engine/src/trading/roundTripBuild.ts: the live bot's pre-flight
// harness (contracts/test/sim/BotRoundTrip.sol), runtime code and ABI, from
// `forge build`.
//
//   forge build contracts/test/sim/BotRoundTrip.sol && bun engine/scripts/gen-roundtrip-build.ts
//   … && bun engine/scripts/gen-roundtrip-build.ts --check     # is it current?
//
// The harness is never deployed: the bot puts this code at its own wallet's
// address for one eth_call before each live buy (engine/src/trading/preflight.ts).
// --check compares the code without its trailing metadata (a hash of the
// compiler's input, which differs between solc front ends for the same code).
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const ART = 'contracts/out/BotRoundTrip.sol/BotRoundTrip.json'
const TARGET = 'engine/src/trading/roundTripBuild.ts'
if (!existsSync(ART)) { console.error(`${ART} not found: run forge build first`); process.exit(1) }
interface Artifact { abi: unknown[]; deployedBytecode: { object: string }; metadata: { compiler: { version: string }; settings: { viaIR: boolean; optimizer: { runs: number }; evmVersion: string } } }
const a = JSON.parse(readFileSync(ART, 'utf8')) as Artifact
const s = a.metadata.settings
const code: string = a.deployedBytecode.object
const body = `// Generated by engine/scripts/gen-roundtrip-build.ts from \`forge build\`: do not edit.
// contracts/test/sim/BotRoundTrip.sol, solc ${a.metadata.compiler.version}, via-IR ${s.viaIR}, optimizer ${s.optimizer.runs} runs, EVM ${s.evmVersion}.

export const ROUNDTRIP_ABI = ${JSON.stringify(a.abi)} as const

/** Runtime code, put at the bot wallet's address by a state override for one eth_call. */
export const ROUNDTRIP_RUNTIME = ${JSON.stringify(code)} as const
`
/** The code without the CBOR metadata solc appends (its length is the last two bytes). */
const bare = (hex: string) => { const h = hex.replace(/^0x/, ''); const n = parseInt(h.slice(-4), 16); return h.slice(0, h.length - (n + 2) * 2) }
if (process.argv.includes('--check')) {
  const cur = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : ''
  const m = /ROUNDTRIP_RUNTIME = "(0x[0-9a-f]+)"/.exec(cur)
  if (!m || bare(m[1]) !== bare(code) || !cur.includes(JSON.stringify(a.abi))) { console.error(`${TARGET} is stale: regenerate it`); process.exit(1) }
  console.log(`${TARGET} is current`)
} else {
  writeFileSync(TARGET, body)
  console.log(`wrote ${TARGET} (${(code.length - 2) / 2} bytes of runtime code)`)
}
