// Writes engine/src/intel/probeBuild.ts: the honeypot probe's runtime code
// and ABI (contracts/test/sim/HoneypotProbe.sol), from `forge build`.
//
//   forge build contracts/test/sim/HoneypotProbe.sol && bun engine/scripts/gen-probe-build.ts
//   … && bun engine/scripts/gen-probe-build.ts --check     # is it current?
//
// The probe is never deployed: the scanner injects this code with an
// eth_call state override (engine/src/intel/honeypot.ts).
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const ART = 'contracts/out/HoneypotProbe.sol/HoneypotProbe.json'
const TARGET = 'engine/src/intel/probeBuild.ts'
if (!existsSync(ART)) { console.error(`${ART} not found: run forge build first`); process.exit(1) }
const a = JSON.parse(readFileSync(ART, 'utf8'))
const s = a.metadata.settings
const body = `// Generated by engine/scripts/gen-probe-build.ts from \`forge build\`: do not edit.
// contracts/test/sim/HoneypotProbe.sol, solc ${a.metadata.compiler.version}, via-IR ${s.viaIR}, optimizer ${s.optimizer.runs} runs, EVM ${s.evmVersion}.

export const PROBE_ABI = ${JSON.stringify(a.abi)} as const

/** Runtime code, injected at PROBE_ADDRESS by a state override. */
export const PROBE_RUNTIME = ${JSON.stringify(a.deployedBytecode.object)} as const
`
if (process.argv.includes('--check')) {
  const cur = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : ''
  if (cur !== body) { console.error(`${TARGET} is stale: regenerate it`); process.exit(1) }
  console.log(`${TARGET} is current`)
} else {
  writeFileSync(TARGET, body)
  console.log(`wrote ${TARGET} (${(a.deployedBytecode.object.length - 2) / 2} bytes of runtime code)`)
}
