// Generated by engine/scripts/learn-templates.ts from contracts on Arc mainnet: do not edit.
// Learned 2026-09-29. Still current? bun engine/scripts/learn-templates.ts --check

import type { CodeTemplate } from './templates'

export const TEMPLATES: Record<string, CodeTemplate> = {
  "Peach curve": {
    "name": "Peach curve",
    "size": 15728,
    "mask": [
      [
        1276,
        1295
      ],
      [
        2665,
        2668
      ],
      [
        2759,
        2778
      ],
      [
        3048,
        3049
      ],
      [
        3968,
        3969
      ],
      [
        4027,
        4029
      ],
      [
        4420,
        4424
      ],
      [
        4543,
        4562
      ],
      [
        5379,
        5398
      ],
      [
        6471,
        6490
      ],
      [
        7255,
        7274
      ],
      [
        8271,
        8290
      ],
      [
        8510,
        8529
      ],
      [
        9085,
        9104
      ],
      [
        9181,
        9200
      ],
      [
        9549,
        9568
      ],
      [
        10325,
        10328
      ],
      [
        10694,
        10713
      ],
      [
        10805,
        10824
      ],
      [
        11586,
        11588
      ],
      [
        11708,
        11727
      ],
      [
        12564,
        12583
      ],
      [
        13623,
        13624
      ]
    ],
    "hash": "0x492332523b68d337320548ca403cf82a7b824a1133ca9b7fa0355b1c41af0fdc",
    "fields": {
      "quote": 0
    }
  }
}
