// Generated by engine/scripts/learn-templates.ts from contracts on Arc mainnet: do not edit.
// Learned 2026-09-30. Still current? bun engine/scripts/learn-templates.ts --check

import type { CodeTemplate } from './templates'

export const TEMPLATES: Record<string, CodeTemplate> = {
  "Argus P7 hook": {
    "name": "Argus P7 hook",
    "size": 5175,
    "mask": [
      [
        476,
        507
      ],
      [
        825,
        856
      ],
      [
        914,
        945
      ],
      [
        1734,
        1765
      ],
      [
        1772,
        1803
      ],
      [
        1874,
        1905
      ],
      [
        2151,
        2182
      ],
      [
        2753,
        2784
      ],
      [
        2799,
        2830
      ]
    ],
    "hash": "0x99e17c1cf48b29928e77a55aec26932a5cc75889f9be9b9590d52e914d6eec45"
  },
  "Argus P8 token": {
    "name": "Argus P8 token",
    "size": 5116,
    "mask": [],
    "hash": "0x6d674fc1836493a18d67495de0ec88fad91599a8c403f3c91333df7659b4e600"
  },
  "Argus P8 hook": {
    "name": "Argus P8 hook",
    "size": 10423,
    "mask": [
      [
        804,
        835
      ],
      [
        1315,
        1346
      ],
      [
        1402,
        1433
      ],
      [
        1736,
        1767
      ],
      [
        3725,
        3756
      ],
      [
        4011,
        4042
      ],
      [
        4571,
        4602
      ],
      [
        4618,
        4649
      ],
      [
        4875,
        4906
      ],
      [
        5041,
        5072
      ],
      [
        5758,
        5789
      ],
      [
        5833,
        5864
      ],
      [
        6705,
        6736
      ],
      [
        7048,
        7079
      ],
      [
        7086,
        7117
      ],
      [
        7360,
        7391
      ],
      [
        7398,
        7429
      ]
    ],
    "hash": "0x636c1ebffc13dcd31d6ac6591fc8d0c49f5c05ff569631db8a8d0437d91100f1",
    "fields": {
      "escrow": 0
    }
  },
  "Peach token": {
    "name": "Peach token",
    "size": 3299,
    "mask": [
      [
        739,
        770
      ],
      [
        960,
        991
      ]
    ],
    "hash": "0x5c0f93833ff5021fe7588826dabcd301f129accfc269e9c93b233948513053d3"
  },
  "Faze token": {
    "name": "Faze token",
    "size": 2665,
    "mask": [],
    "hash": "0x28520a39b468c230e2c0af9cdd5524eba393cfab5a3f13a5301519f726b00720"
  },
  "Mercuri token": {
    "name": "Mercuri token",
    "size": 1781,
    "mask": [],
    "hash": "0x4130e82a45554f1f86116dc497e62ab5dd14fbc9d726f443b7e59b883a098fb8"
  },
  "SolonPad token": {
    "name": "SolonPad token",
    "size": 3194,
    "mask": [
      [
        379,
        410
      ],
      [
        529,
        560
      ],
      [
        1094,
        1125
      ]
    ],
    "hash": "0x1db4667330e189ec2cbc19bc96bb74815f0cfc40e2bd995f84710ca588f37682"
  },
  "Aka.fun token": {
    "name": "Aka.fun token",
    "size": 14874,
    "mask": [
      [
        1021,
        1052
      ],
      [
        1694,
        1725
      ],
      [
        3756,
        3787
      ],
      [
        4584,
        4615
      ],
      [
        6056,
        6087
      ],
      [
        6491,
        6522
      ],
      [
        7177,
        7208
      ],
      [
        10700,
        10731
      ],
      [
        10754,
        10785
      ],
      [
        10833,
        10864
      ]
    ],
    "hash": "0xcffb0d964c96433f8993ee4b40838ac88604f663e7fd3cf9fc2f5362fbf6b140"
  },
  "o1 token": {
    "name": "o1 token",
    "size": 4724,
    "mask": [
      [
        692,
        723
      ],
      [
        1265,
        1296
      ],
      [
        1574,
        1605
      ],
      [
        1701,
        1732
      ],
      [
        2197,
        2228
      ],
      [
        2747,
        2778
      ]
    ],
    "hash": "0xdad72031da9bec7eacd336ca7d1b7e3b517e9179d0fec33f819787b5d370628b"
  },
  "Minara token": {
    "name": "Minara token",
    "size": 7154,
    "mask": [
      [
        717,
        748
      ],
      [
        1473,
        1504
      ],
      [
        2996,
        3027
      ]
    ],
    "hash": "0xfb3288fd4fb725df6bff7241d44c458e26a543efb5cb689527c3b441d8c89330"
  },
  "Peach curve": {
    "name": "Peach curve",
    "size": 15728,
    "mask": [
      [
        1264,
        1295
      ],
      [
        2637,
        2668
      ],
      [
        2747,
        2778
      ],
      [
        3018,
        3049
      ],
      [
        3938,
        3969
      ],
      [
        3998,
        4029
      ],
      [
        4393,
        4424
      ],
      [
        4531,
        4562
      ],
      [
        5367,
        5398
      ],
      [
        6459,
        6490
      ],
      [
        7243,
        7274
      ],
      [
        8259,
        8290
      ],
      [
        8498,
        8529
      ],
      [
        9073,
        9104
      ],
      [
        9169,
        9200
      ],
      [
        9537,
        9568
      ],
      [
        10297,
        10328
      ],
      [
        10682,
        10713
      ],
      [
        10793,
        10824
      ],
      [
        11557,
        11588
      ],
      [
        11696,
        11727
      ],
      [
        12552,
        12583
      ],
      [
        13593,
        13624
      ]
    ],
    "hash": "0xcc3eb29ed2747627f5269fabbf81dcf850ddf5278ae23f457e2ebde6f6fe7cc7",
    "fields": {
      "quote": 0
    }
  }
}
